# Site settings
title: HOV Blog
SEOTitle: 王昊的博客 | HOV Blog
header-img: img/post-bg-desk.jpg
email: njustwanghao@163.com
description: "Every failure is leading towards success."
keyword: "HOV, HOV Blog, 王昊的博客, prajna1991, 王昊, iOS, Apple, iPhone"
url: "http://prajna1991.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Get things right!"
sidebar-avatar: /img/avatar-m     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     su-zhi-13-90
zhihu_username:     su-zhi-13-90
github_username:    prajna1991
#twitter_username:   su-zhi-13-90




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e105bf9238c0716afd1e                            #生成的clientID
  clientSecret: aa0d0971e8fbbf59af7c0ca5d52f24727a9ec05d    #生成的clientSecret
  repo: prajna1991.github.io    #仓库名称
  owner: prajna1991   #github用户名
  admin: prajna1991
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-131085968-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
